jobs: 

 

- job: 'test'

  pool: 

    vmImage: 'windows-latest'

  strategy: 

    matrix: 

      Python310: 

        python.version: '3.10'

    maxParallel: 1

  

  steps: 

  - task: UsePythonVersion@0

 

    inputs: 

      versionSpec: '$(python.version)'

      architecture: 'x64'

  

  - script: pip install robotframework-seleniumlibrary && npm install chromedriver

    displayName: 'install dependences'

   

  - powershell: robot --pythonpath . sprint3_test.robot

    displayName: 'Run Robot Scripts'

  

  - task: PublishTestResults@2

    inputs:

      testResultsFormat: 'XUnit'

      testResultsFiles: 'output.xml'

      searchFolder: 'D:\a\1\s\'

      failTaskOnFailedTests: true